<section id="Vanoce2017" class="features" style=" background-image: url(img/2017-vanoce-sec2.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
				Štědrý den v Seči.
			</h2>
            <br />
            <a href="./2017_12_24-Sec-betlem3.pdf" class="btn btn-danger btn-lg" role="button"><i class="fas fa-child fa-fw"></i>Návštěva betléma</a>
            <a href="./2017-vanoce.pdf" class="btn btn-info btn-lg" role="button"><i class="fas fa-tree fa-fw"></i>Vánoční bohoslužby</a>
		</div>
	</div>
</section>