<section id="Vanoce2017" class="features" style=" background-image: url(img/2017-vanoce-sec2.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<img src="img/black_star_4.svg" style="width: 5em; transform: rotate(60deg);" class="rounded float-right" alt="Hvězda"><br />
			<h2>
				24. 12.<br />
				Štědrý den v Seči
			</h2>
			<br />
            <br />
            <a href="./2017_12_24-Sec-betlem3.pdf" class="btn btn-danger btn-lg" role="button"><i class="fas fa-child fa-fw"></i>Setkání u betléma</a>
            <a href="./2017-vanoce.pdf" class="btn btn-info btn-lg" role="button"><i class="fas fa-tree fa-fw"></i>Vánoční bohoslužby</a>
		</div>
	</div>
</section>