<section id="Vanoce2017" class="features" style=" background-image: url(img/2017-becket.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<img src="img/mec.svg" style="width: 3em; transform: rotate(240deg);" class="rounded float-right" alt="Hvězda"><br />
			<h2>
                29. 12.<br />
                Nedokončené nešpory
			</h2>
			<br />
            <br />
            <a href="./2017_12_29-Sec-Becket.pdf" class="btn btn-danger btn-lg" role="button"><i class="fas fa-heartbeat fa-fw"></i>Nedokončené nešpory</a>
            <a href="./2017-vanoce.pdf" class="btn btn-info btn-lg" role="button"><i class="fas fa-tree fa-fw"></i>Vánoční bohoslužby</a>
		</div>
	</div>
</section>