<section id="Svatopost2018" class="features">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<img src="img/2018-svatopost.jpg" style="width:100%;">
		<div style="width:52.4%; background-color:red;height: 100px;">
			nvim
		</div>
		<div class="heslodne" style="color:black;">
			<img src="img/mec.svg" style="width: 3em; transform: rotate(240deg);" class="rounded float-right" alt="Hvězda"><br />
			<h2>
                29. 12.<br />
                Nedokončené nešpory
			</h2>
			<br />
            <br />
            <a href="./pdf/2017_12_29-Sec-Becket.pdf" class="btn btn-danger btn-lg" role="button"><i class="fas fa-heartbeat fa-fw"></i>Nedokončené nešpory</a>
            <a href="./pdf/2017-vanoce.pdf" class="btn btn-info btn-lg" role="button"><i class="fas fa-tree fa-fw"></i>Vánoční bohoslužby</a>
		</div>
	</div>
</section>