<section id="Velikonoce20184" class="features" style="background-image: url(img/2018-pieta.jpg); background-repeat:no-repeat; background-size: cover; background-position:left center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;text-align:center;font-size:3.5em;">
		<div style="color:white; margin:1em 0; line-height:120%;text-shadow: 1px 1px 2px black;">
            Velikonoční žalmy na Seči<br />
        </div>
        <div style="color:white; margin:3em 0; line-height:120%;text-shadow: 1px 1px 2px black;">
        pátek, sobota<br />
        8.00h<br />
        </div>
    </div>
</section>