<section id="Velikonoce22018" class="features"  style="background-color:white;">
	<div class="container" style="margin-top: 10em; margin-bottom: auto;">
		<div class="row">
			<div class="sec-title text-center">
				<h2>Velikonoční svátky</h2>
			</div>
			<div style="text-align: left; font-weight:400; font-size:20px; margin-left: auto; margin-right: auto;width:430px;">
				<p class="veliDen">čt 29. 3. Zelený čtvrtek</p>
                <p class="veliMisto">Míčov</p>
                <p class="veliCas" style="color: black; font-size:1.3em;"><span class="veliTime">18.00h</span>Památka pesachové večeře</p>
                <p class="veliDen">pá 30. 3. Velká pátek</p>
                <p class="veliMisto">Seč</p>
                <p class="veliCas"><span class="veliTime">8.00h</span>modlitba žalmů</p>
                <p class="veliMisto">Míčov</p>
                <p class="veliCas"><span class="veliTime">9.00h</span>hrkání v obci<br /><span class="veliTime">12.00h</span>hrkání v obci</p>
                <p class="veliCas" style="color: black; font-size:1.3em;"><span class="veliTime">15.00h</span>Pašije</p>
                <p class="veliCas"><span class="veliTime">19.00h</span>hrkání v obci<br />
                    <span class="veliTime"> </span>ukládání Ježíše do hrobu</p>
                <p class="veliDen">so 31. 3. Bílá sobota</p>
                <p class="veliMisto">Seč</p>
                <p class="veliCas"><span class="veliTime">8.00h</span>modlitba žalmů</p>
                <p class="veliMisto">Míčov</p>
                <p class="veliCas"><span class="veliTime">9.00h</span>hrkání v obci<br /><span class="veliTime">12.00h</span>hrkání v obci<br /><span class="veliTime">19.00h</span>hrkání v obci</p>
                <p class="veliCas" style="color: black; font-size:1.3em;"><span class="veliTime">21.00h</span>Noc Vzkříšení</p>
                <p class="veliDen">ne 1. 4. Neděle Vzkříšení</p>
                <p class="veliMisto">Ronov nad Doubravou</p>
                <p class="veliCas"><span class="veliTime">8.00h</span>slavnost Vzkříšení</p>
                <p class="veliMisto">Seč</p>
                <p class="veliCas"><span class="veliTime">9.30h</span>slavnost Vzkříšení</p>
                <p class="veliMisto">Běstvina</p>
                <p class="veliCas"><span class="veliTime">11.00h</span>slavnost Vzkříšení</p>
			</div>
		</div>
	</div>
</section>