<section id="Velikonoce20184" class="features" style="background-image: url(img/2018-tenebrae.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;text-align:center;font-size:3.5em;">
		<div style="color:white; margin:1em 0; line-height:120%;">
            Velikonoční žalmy na Seči<br />
        </div>
        <div style="color:white; margin:3em 0; line-height:120%;">
        pátek, sobota<br />
        8.00h<br />
        </div>
    </div>
</section>