<section id="Svatopost2018" class="features" style="background-color:white;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">

		
		<div style="text-align:center;color:white;position: relative;">
			<img src="img/2018-svatopost.jpg" style="width: 100%;">
			<div style="top:50%;left:50%;transform: translate(-50%, -50%);position: absolute;font-size:13vw;font-weight:300;text-shadow: 2px 2px black;line-height:1em">Abrahám<br />a Sára.</div>
		</div>
		<div style="background-color:black; color:gold; font-size:1.5em; padding:1em 0; text-align:center">
				biblické žalmy a&nbsp;příběh Abrahámovy životní cesty
			</div>	
		<div style="font-size:1.5em;color:black;text-align:center;line-height:120%;margin:1em 0;">každý pátek od 18.00 hod. v&nbsp;kostele sv.&nbsp;Vavřince v&nbsp;Seči<a href="./ohlasky.pdf" style="color:#8C2318;margin-left:1em;" title="Aktuální ohlášky"><i class="far fa-file-pdf"></i></a></div>
	</div>
</section>