<section id="Velikonoce2018" class="features" style="background-image: url(img/2018-velikonoce.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;text-align:center;font-size:3.5em;">
		<div style="color:white; margin:1em 0; line-height:120%">
            Velikonoce na Míčově<br />
            29.–31. 3. 2018
        </div>
        
        <div style="color:black; margin:3em 0; line-height:120%">
        18.00h čtvrtek<br />
        15.00h pátek<br />
        21.00h sobota<br />
        </div>
    </div>
</section>
<section id="Velikonoce20182" class="features" style="background-image: url(img/2018-klapacky.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;text-align:center;font-size:3.5em;">
		<div style="color:black; margin:1em 0; line-height:120%">
            Velikonoční hrkání na Míčově<br />
        </div>
        
        <div style="color:white; margin:3em 0; line-height:120%;text-shadow: 1px 1px 2px black;">
        pátek, sobota<br />
        9.00h — 12.00h — 19.00h<br />
        </div>
    </div>
</section>
<section id="Velikonoce20183" class="features" style="background-image: url(img/2018-ecce.jpg); background-repeat:no-repeat; background-size: cover; background-position:right center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;text-align:center;font-size:3.5em;">
		<div style="color:white; margin:1em 0; line-height:120%;text-shadow: 1px 1px 2px black;">
            Velikonoce na Míčově<br />
            „Ecce Abraham et Sara“<br />
        </div>
        
        <div style="color:white; margin:3em 0; line-height:120%;text-shadow: 1px 1px 2px black;">
        pátek, sobota<br />
        cca 19.10h<br />
        </div>
    </div>
</section>