<section id="Velikonoce2018" class="features" style="background-image: url(img/2018-velikonoce.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;text-align:center;font-size:3.5em;">
		<div style="color:white; margin:1em 0; line-height:120%">
            Velikonoce na Míčově<br />
            29.–31. 3. 2018
        </div>
        
        <div style="color:black; margin:3em 0; line-height:120%">
        18.00h čtvrtek<br />
        15.00h pátek<br />
        21.00h sobota<br />
        </div>
    </div>
</section>