<section id="heslodne" class="features" style="background-image: url(img/HD-1901-mezi.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
                <span>Věrohodnost křesťanů.</span>
            </h2>
			<br />
		    <br />
            <p> Věrohodnost se rodí z&nbsp;důvěry,<br />
                a&nbsp;důvěra se rodí z&nbsp;velkorysé služby každému člověku:<br />
                služby, jenž nevede k získání společenského uznání a&nbsp;prestiže,<br />
                ale dotýká se „tepajícího srdce evangelia“.<br />
                <br />
               <em style="font-size:.8em;text-align: right">podle František: Dopis biskupů USA (1.&nbsp;1.&nbsp;2019)</em><br />
            </p>
		</div>
	</div>
</section>