<section id="heslodne" class="features" style="background-image: url(img/HD-1903-svatopost.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
                <span>Svatopostní doba.</span>
            </h2>
			<br />
		    <br />
            <p> Pokud se lidské životy nechávají<br />
                proměňovat láskou ke Kristu, je tím vzdávána chvála Bohu.<br /><br />
                <b>Modlitba</b>, <b>rozjímání</b> a&nbsp;<b>cit pro umění</b> do ní zahrnuje všechno stvoření.<br />
                <br />
               <em style="font-size:.8em;text-align: right">podle František: Svatopostní poselství (2019); Yara Said: Prayer (2017).</em><br /><br />
            </p>
		</div>
	</div>
</section>