<section id="heslodne" class="features" style="background-image: url(img/HD-1907b-mezidobi.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6); animation-name: color; animation-duration: 8s; animation-iteration-count: infinite;">
			<h2>
                <span>Otče náš, jenž jsi na nebesích…</span>
            </h2>
			<br />
		    <br />
            <p> Nikdo nevěděl, kde má duše může být.<br />
                Hledal jsem Boha, ne a&nbsp;ne ho objevit.<br />
                Bratra jsem vyhledal&nbsp;– a&nbsp;našel všechny tři.<br />
                <br />
               <em style="font-size:.8em;text-align: right">Ernest H. Crosby (1856–1907): The Search. || Tiago Galo: Rip it or fill it.</em><br /><br />
            </p>
		</div>
	</div>
</section>