<section id="heslodne" class="features" style="background-image: url(img/HD-1912-vanoce.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2>
                <span>Hvězdy na Východě</span>
            </h2>
			<br />
		    <br />
            <p> Hle, hvězda, kterou mudrci viděli na východě,<br />
                šla před nimi, až se zastavila nad místem, kde bylo dítě.<br />
                <br />
                Na Východě je slyšet hlas, pláč a&nbsp;velké bědování:<br />
                Matka oplakává svoji děti. Není k&nbsp;utišení –&nbsp;už nejsou.<br />
                <br />
                Ježíš řekl: „Já jsem s vámi po všechny dny až do konce světa!“<br />
                <br />
               <em style="font-size:.8em;text-align: right">srov. Mt 2,&nbsp;9.18; 28,&nbsp;20 || AP/Ariel Schalit (4.&nbsp;5.&nbsp;2019)</em><br /><br />
            </p>
		</div>
	</div>
</section>