<section id="heslodne" class="features" style="background-image: url(img/HD-Toufar.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
        		<span>P. Josef Toufar v Číhošti</span>
			</h2>
			<br />
		    
            <p><b>neděle 24/2/2019</b><br /><br />
                <b>Mše sv.</b> a&nbsp;<b>beseda</b> s&nbsp;P.&nbsp;Josefem Kordíkem, dlouholetým vězeňským kaplanem a&nbsp;chartistou<br />
               <br />
            </p>
		</div>
	</div>
</section>