<section id="heslodne" class="features" style="background-image: url(img/HD-Kate_Evangs-Pregnancy.jpg.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2>
                <span>Adventní sen o&nbsp;dítěti</span>
            </h2>
			<br />
		    <br />
            <p> Nepřipusť, aby strachy, starosti,<br />
                komentáře ostatních nebo problémy<br />
                zadusily tvoji radost z&nbsp;toho,<br />
                že jsi Božím nástrojem,<br />
                který přináší na svět nový život.<br />
                <br />
               <em style="font-size:.8em;text-align: right">František: Amoris lætitia (2016), čl.&nbsp;171. || Kate Evans</em><br /><br />
            </p>
		</div>
	</div>
</section>