<section id="heslodne" class="features" style="background-color: #ffffff; animation-name: color; animation-duration: 8s; animation-iteration-count: infinite;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
                <span>Otče náš, jenž jsi na nebesích.</span>
            </h2>
			<br />
		    <br />
            <p> Nikdo nevěděl, kde má duše může být.<br />
                Hledal jsem Boha, ne a&nbsp;ne ho objevit.<br />
                Bratra jsem vyhledal&nbsp;– a&nbsp;našel všechny tři.<br />
                <br />
               <em style="font-size:.8em;text-align: right">Ernest H. Crosby (1856–1907): The Search.</em><br /><br />
            </p>
		</div>
	</div>
</section>