<section id="heslodne" class="features" style="background-image: url(img/HD-1904-velikonoce.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
                <span style="text-shadow: -2px 0 1px rgb(30,242,241) , 2px 0 1px rgb(246,5,10), 1px 1px 1px yellow;">Velikonoční avantgarda.</span>
            </h2>
			<br />
		    <br />
            <p>Evangelium není pouhým sdělením čehosi, co je možné se dozvědět.<br />
                Jde o performativní sdělení, které účinně působí, vytváří skutečnosti a&nbsp;mění život.<br />
                Temná vrata času, budoucnosti, byla otevřena dokořán.<br />
                Kdo má naději, žije jinak; byl mu darován nový život.<br />
                <br />
               <em style="font-size:.8em;text-align: right">podle Benedikt&nbsp;XVI: Spe salvi, čl.&nbsp;2 (2017); Kazimir Malevič: Bílý na bílém (1918).</em><br /><br />
            </p>
		</div>
	</div>
</section>