<section id="heslodne" class="features" style="background-image: url(img/HD-2021-12-toufar.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span><a style="color: black;" href="img/12-12_2021-vzpominka-cihost.jpg">Číhošťské události 1949</a></span>
			</h2>
			<br />
            <br />
            <p>
                Vzpomínka v neděli 12. 12. 2021 v Číhošti.<br />
                Celebrantem a hostem následné besedy je <strong>P. Pavel Kuneš</strong>.<br />
                <br />
            </p>
		</div>
	</div>
</section>