<section id="heslodne" class="features" style="background-image: url(img/HD-2022-12-vanoce.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Otevřená nebesa</span>
			</h2>
			<br>
		    <br>
            <p>
                „Hle, dívka počne a&nbsp;porodí syna<br>
                a&nbsp;dá mu jméno <i>Bůh s&nbsp;námi</i>.“ (Iz&nbsp;7,&nbsp;14)<br>
                <br>
                Vánoce prolamují zdi ideologií a&nbsp;vtělení.<br>
                Posouvají rozum k srdci, ideje ke skutkům.<br>
                Slova se stávají tělem a přebývají mezi námi. (Jan&nbsp;1,&nbsp;14)<br>
                <br>
                <em style="font-size:.8em;text-align: right">S.&nbsp;Erickson: Honest advent, 2020.</em><br><br> 
            </p>
		</div>
	</div>
</section>

