<section id="heslodne" class="features" style="background-image: url(img/HD-2021-01-podgorica.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Světla i stíny</span>
			</h2>
			<br />
            <br />
            <p>Víra nenabízí povrchní a uklidňující řešení.<br />
            Víru, které učí Kristus, vidíme u sv. Josefa.<br />
            Nehledá zkratky. Realitu nahlíží otevřenýma očima<br />
            a přijímá za ni odpovědnost.<br />
               <br />
               <em style="font-size:.8em;text-align: right">František: Patris corde (2020); Podgorica, Černá Hora (1920)</em><br /><br />
            </p>
		</div>
	</div>
</section>

