<section id="heslodne" class="features" style="background-image: url(img/HD-2026-04-veli.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Křestní pomazání</span>
			</h2>
			<br>
            <p>
				Pomazání proniká do nejhlubšího nitra naší existence:<br>
				Boží Duch pomazává naše slabosti,<br>
				naši únavu, naši vnitřní chudobu;<br>
				přináší novou vůni: ne odér našeho ega,<br>
				ale jemnost Ducha.<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. František: homilie (6. 4. 2023); C. Crivelli: Máří Magdalena (1480)</em><br><br> 
            </p>
		</div>
	</div>
</section>

