<section id="heslodne" class="features" style="background-image: url(img/HD-2021-03-svaty_tyden3.svg); background-color: #F5DF4D; background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Vyvýšeni v evangeliu</span>
			</h2>
			<br />
            <br />
            <p>
                Ten kdo nás povolal, nám umožňuje <em>pozvednout</em> hlavu a&nbsp;začít znovu.<br />
                Neutíkejme před Ježíšovým vzkříšením,<br />
                nikdy se nevzdávejme, ať se děje, co se děje.<br />
                Nic není mocnější než jeho život, jenž nás žene kupředu!<br />
               <br />
               <em style="font-size:.8em;text-align: right">František: Evangelii gaudium (2013), čl.&nbsp;3</em><br /><br /> 
            </p>
		</div>
	</div>
</section>