<section id="heslodne" class="features" style="background-image: url(img/HD-2002-svatopost.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2>
                <span>Touha žít v&nbsp;přítomnosti</span>
            </h2>
			<br />
		    <br />
            <p>
                Následuj své naděje a&nbsp;sny…<br />
                <br />
                Vyvaruj se ochrnutí <i>živých mrtvých</i>, kteří v&nbsp;sobě nemají život,<br />
                protože nechtějí riskovat nebo mají strach dělat chyby.<br />
                <br />
                I když se zmýlíš, můžeš se vždycky zvednout a&nbsp;začít znovu.<br />
                Nikdo nemá právo oloupit tě o&nbsp;naději.<br />
                <br />
               <em style="font-size:.8em;text-align: right">srov. František: Christus vivit, čl.&nbsp;142 || Ilir Pojani: Indecision, 2015.</em><br /><br />
            </p>
		</div>
	</div>
</section>