<section id="heslodne" class="features" style="background-color: #970707">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:e5e6df;">
			<h2>
        		<span>#RedWednesday</span>
			</h2>
			<br />
		    <br />
            <p>„Když jsem roku 2006 přišel do Damašku,<br />
                nemohl jsem najít chudého člověka,<br />
                který by zrovna potřeboval mou pomoc…<br />
                Osm let války však rozbilo zemi i&nbsp;mírumilovný národ.“<br />
               <br />
               <em style="font-size:.8em;text-align: right">+&nbsp;Samir NASSAR: Pâques 2019 (Damašek, Sýrie)</em><br /><br />
            </p>
		</div>
	</div>
</section>