<section id="heslodne" class="features" style="background-image: url(img/HD-2021-02-svatopost.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Vyvýšeni v evangeliu</span>
			</h2>
			<br />
            <br />
            <p>
                Učedníci uslyšeli Ježíšovo povolání k přátelství s ním.<br />
                Bylo to pozvání, které na ně netlačilo,<br />
                ale které laskavě naléhalo na jejich svobodu.<br />
               <br />
               <em style="font-size:.8em;text-align: right">František: Christus vivit (2019), čl. 153</em><br /><br /> 
            </p>
		</div>
	</div>
</section>

