<section id="heslodne" class="features" style="background-image: url(img/HD-2026-05-nockostelu.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne">
			<img src="img/nockostelu2.svg" alt="Noc kostelů" style="width: 70%; margin-top: 5%; margin-bottom: 5%;">

			<br>
            <p>
				pátek 29. května 2026<br><br>
				<a style="color:black; font-weight:bold;" href="https://nockostelu.cz/kostel/1161/">Světlá nad Sázavou 🔗</a><br>
				<a style="color:black; font-weight:bold;" href="https://nockostelu.cz/kostel/1911/">Číhošť 🔗</a><br>
				<br>
            </p>
		</div>
	</div>
</section>

