<section id="heslodne" class="features" style="background-image: url(img/HD-2025-12-vanoce.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Zrození naděje</span>
			</h2>
			<br>
            <p>
                U&nbsp;Césareje Filipovy se Ježíš zeptal svých učedníků:<br>
				„Za koho lidé pokládají Syna člověka?“<br>
				„Jedni za Jana Křtitele, druzí za Eliáše, Jeremiáše…“<br>
				„A&nbsp;za koho mě pokládáte vy?“<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. Mt 16, 13–15; J.&nbsp;Cleve: Svatý rodina (1512)</em><br><br> 
            </p>
		</div>
	</div>
</section>

