<section id="heslodne" class="features" style="background-image: url(img/HD-2026-02-svatopost.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Bez vědra</span>
			</h2>
			<br>
            <p>
				Voda, která dává věčný život,<br>
				byla vylita do našich srdcí v&nbsp;den našeho křtu.<br>
				Ale možná jsme na tento veliký dar zapomněli…<br>
				nebo jsme jej zredukovali na „úřední záznam“…<br>
				možná hledáme i další „studny“, jejichž voda<br>
				by snad uhasila naši žízeň po pokojném životě.<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. František: Angelus (19. 3. 2017); <a style="color: black;" href="http://hdl.loc.gov/loc.pnp/fsa.8a23374">LC-DIG-fsa-8a23374</a></em><br><br> 
            </p>
		</div>
	</div>
</section>

