<section id="heslodne" class="features" style="background-image: url(img/HD-2022-06-nockostelu.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:#fee303;">
			<h2 style="line-height: 1; padding-top: .4em">
        		<span style="font-weight: 900; text-shadow: 2px 2px black; font-size: larger;">NOC KOSTELŮ</span>
			</h2>
			<br />
		    <br />
            <p style="text-shadow: 1px 1px black; font-weight: bolder;">
                10.06.22&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a style="color:#fee303;" href="https://nockostelu.cz/kostel/1161/">Světlá nad Sázavou</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a style="color:#fee303;" href="https://nockostelu.cz/kostel/1911/">Číhošt</a><br />
                <br />
            </p>
		</div>
	</div>
</section>

