<section id="heslodne" class="features" style="background-image: url(img/HD-2023-01-mezi.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Větší i&nbsp;menší naděje</span>
			</h2>
			<br>
		    <br>
            <p>
                Boží království není jakýsi imaginární <i>onen svět</i>…<br>
                Jen jeho láska nám umožňuje, abychom ve vší střízlivosti,<br>
                den po dni vytrvali ve světě, který je nedokonalý,<br>
                a&nbsp;neztráceli elán naděje.<br>
                <br>
                <em style="font-size:.8em;text-align: right">Benedikt XVI.: Spe salvi, čl.&nbsp;31; Pavlo Suško, Vovčansk (2022)</em><br><br> 
            </p>
		</div>
	</div>
</section>

