<section id="heslodne" class="features" style="background-image: url(img/HD-2023-04-velikonoce.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Život ve společenství</span>
			</h2>
			<br>
            <p>
                Křtem jsem ponořeni jak do učení,<br>
                které má být vyznáváno,<br>
                tak do konkrétního způsobu života,<br>
                který vyžaduje zapojení celé osoby<br>
                a&nbsp;uvádí nás na cestu dobra.<br>
                <br>
                <em style="font-size:.8em;text-align: right">srov. Benedikt XVI.: Lumen fidei, 2013, čl. 41; Křest v Seven Wells, Texas, 1922.</em><br><br> 
            </p>
		</div>
	</div>
</section>

