<section id="heslodne" class="features" style="background-image: url(img/HD-2024-04-veli.jpg); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>„Jděte a&nbsp;povězte to ostatním“</span>
			</h2>
			<br>
            <p>
                Naším prostřednictvím se všude šíří vůně poznání o&nbsp;Kristu.<br>
				Jsme Bohu jako vonné kadidlo vydechující Krista.<br>
				Je to vůně životodárná, vedoucí k životu.<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. 2 Kor 2, 14-16. Henri Fantin-Latour, Letní květiny, 1880.</em><br><br> 
            </p>
		</div>
	</div>
</section>

