<section id="heslodne" class="features" style="background-image: url(img/HD-2026-01-leden-2.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Naděje v dějinách</span>
			</h2>
			<br>
            <p>
                Křesťanství nevzešlo z&nbsp;dobrého nápadu, ale z&nbsp;tělesnosti.<br>
				Nezrodilo se z abstraktního konceptu,<br>
				ale z&nbsp;lůna, lidského těla a&nbsp;hrobu.<br>
				Je zakotveno v&nbsp;konkrétních událostech, tvářích, gestech<br>
				a&nbsp;slovech pronesených v&nbsp;určitém jazyce, době a&nbsp;prostředí.<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. Lev XIV.: list o&nbsp;archeologii (2025); 'The De Brailes Hours' (1240)</em><br><br> 
            </p>
		</div>
	</div>
</section>

