<section id="heslodne" class="features" style="background-image: url(img/HD-2001-mezi.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2>
                <span>Naslouchat a sytit se slovem</span>
            </h2>
			<br />
		    <br />
            <p>
                Prorocké působení Písma se projevuje<br />
                především v&nbsp;těch, kteří mu naslouchají.<br />
                <br />
                Vyvolává pocit sladkosti i&nbsp;trpkosti.<br />
                <br />
                Jan na ostrově Patmos vyznává:<br />
                „V&nbsp;mých ústech byla kniha sladká jako med,<br />
                ale když jsem ji snědl, naplnila mé břicho hořkostí.“ (Zj 10,10)<br />
                <br />
               <em style="font-size:.8em;text-align: right">srov. František: Aperuit illis, čl.&nbsp;12 || Paulus Bor: Zklamaná Medea, 1640.</em><br /><br />
            </p>
		</div>
	</div>
</section>