<section id="heslodne" class="features" style="background-image: url(img/HD-2022-02-ukrajina.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>„Kdy jsme tě, Pane, viděli hladového?“</span>
			</h2>
			<br />
		    <br />
            <p>
                Nebeské vojsko, volám u&nbsp;tvých stanů:<br />
                pros za všechny, kdo bloudí na zemi<br />
                v&nbsp;zajetí strašných lží a&nbsp;podlých klamů!<br />
                Nebojuje se dnes jen šavlemi:<br />
                vezme se chleba, máš být bez obživy!<br />
                Bůh neodpírá chleba nikomu…<br />
                <br />
                <em style="font-size:.8em;text-align: right">D.&nbsp;Alighieri: Božská komedie. Ráj&nbsp;XVIII, 124-129 (přel. V.&nbsp;Mikeš); Chris McGrath (2022)</em><br /><br /> 
            </p>
		</div>
	</div>
</section>

