<section id="heslodne" class="features" style="background-image: url(img/HD-2021-09-dante.webp); background-color: #9a7e71; background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Božská komedie svobody</span>
			</h2>
			<br />
            <br />
            <p>
                „Je největší dar, jejž Bůh duši dal<br />
                z&nbsp;nesmírné lásky, dar mu nejvíc milý,<br />
                o&nbsp;který vždycky sám nejvíc stál:<br />
                svobodná vůle, kterou jsou a&nbsp;byly<br />
                obdařeny rozumné bytosti,<br />
                a&nbsp;jenom ony, všecky, co kdy žily.“<br />
                <br />
                <em style="font-size:.8em;text-align: right">D.&nbsp;Alighieri: Božská komedie. Ráj&nbsp;V, 19-24 (přel. V.&nbsp;Mikeš); A.&nbsp;Cotti: Dante a&nbsp;Verona, 1879.</em><br /><br /> 
            </p>
		</div>
	</div>
</section>