<section id="heslodne" class="features" style="background-image: url(img/HD-2003-cetba.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2>
                <span>Lidé, čtěte!</span>
            </h2>
			<br />
		    <br />
            <p>
                I ve vězení mám nápady jak snob<br />
                zatoužil jsem číst knihu Job<br />
                <br />
                *<br />
                <br />
                V úzkostech volal jsem Beránka<br />
                těsná je moje skořápka<br />
                V neklidu nocí v hrůze dní<br />
                prosil jsem ať ji uvolní<br />
                <br />
               <em style="font-size:.8em;text-align: right">Ivan Jirous: Magorovy labutí písně, 1985.</em><br /><br />
            </p>
		</div>
	</div>
</section>