<section id="heslodne" class="features" style="background-image: url(img/HD-2026-06-mezi.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne">
			<h2>Tvář Božího Syna</h2>
			<br>
            <p>
				Důstojnost, kterou do každého z nás vepsal Duch svatý,<br>
				se zjevuje také v naší schopnosti kriticky přemýšlet,<br>
				svobodně volit a milovat, utvářet pravdivé vztahy.<br>
				Žádný výpočetní systém<br>
				nedokáže stvořit srdce, které se daruje,<br>
				ani svědomí, které rozlišuje dobro od zla.<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. Lev XIV.: Magnifica humanitas (15. 5. 2026), čl. 233; H. Hollem: Brave New World (1942)</em><br><br> 
            </p>
		</div>
	</div>
</section>

