<section id="heslodne" class="features" style="background-image: url(img/HD-2012-vanoce.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Vichřice utišila svůj hlas</span>
			</h2>
			<br />
		    <br />
            <p>Učinil ze sebe čisté tělo, oblékl se jím;<br />
                přišel a&nbsp;oblékl naši slabost nebeskou slávou,<br />
                kterou ve svém milosrdenství přinesl od Otce.<br />
               <br />
               <em style="font-size:.8em;text-align: right">Efrém Syrský: hymnus Narození Páně; Henry Ossawa Tanner: Studie (1898)</em><br /><br />
            </p>
		</div>
	</div>
</section>

