<section id="heslodne" class="features" style="background-image: url(img/HD-2012-advent.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Alžběta s Marií</span>
			</h2>
			<br />
		    <br />
            <p>Na počátku křesťanského života<br />
                není etické rozhodnutí nebo velká idea,<br />
                ale setkání s&nbsp;událostí, s&nbsp;Osobou, která otevírá<br />
                před životem nový obzor a&nbsp;dává mu zaměření.<br />
               <br />
               <em style="font-size:.8em;text-align: right">Benedikt XVI: Deus caritas est, čl. 1 (2006)</em><br /><br />
            </p>
		</div>
	</div>
</section>

