<section id="heslodne" class="features" style="background-image: url(img/HD-2024-12-advent.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>„Slunce i hvězdy se zachvějí“</span>
			</h2>
			<br>
            <p>
                Z&nbsp;hvězdy vyšlo slunce,<br>
				nebeské znamení.<br>
				Syn dán jest panence,<br>
				na svět narozený.<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. rorátní zpěvy; Freiburg im Breisgau, Münster</em><br><br> 
            </p>
		</div>
	</div>
</section>

