<section id="heslodne" class="features" style="background-image: url(img/HD-2021-12-vanoce.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Světlo pravé přicházelo na svět</span>
			</h2>
			<br />
		    <br />
            <p>
                Ne, nemám slov, ba ani sil to chápat<br />
                a&nbsp;netroufám si vyložit to blíž,<br />
                s&nbsp;tím „nic“, co vím, zde musím jenom tápat.<br />
                Ó&nbsp;věčné světlo, které v&nbsp;sobě tkvíš,<br />
                jen ty si s&nbsp;láskou hledíš do ohniska,<br />
                jen ty se znáš a&nbsp;sebe vysvětlíš!<br />
                <br />
                <em style="font-size:.8em;text-align: right">D.&nbsp;Alighieri: Božská komedie. Ráj&nbsp;XXXIII, 121-126 (přel. V.&nbsp;Mikeš); anonym: Madona s dítětem (vlámská škola, 16. st.)</em><br /><br /> 
            </p>
		</div>
	</div>
</section>

