<section id="heslodne" class="features" style="background-image: url(img/HD-2021-11-redwed.webp); background-color: #9a7e71; background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>#RedWednesday</span>
			</h2>
			<br />
            <br />
            <p>
                „Podívej se dolů, tam se valí<br />
                veletok krve, všude vroucí krev<br />
                a&nbsp;násilníci do ní napadali.“<br />
                Ach, slepá lačnost a šílený hněv!<br />
                V krátkém životě štvou nás bez okolků<br />
                a navždy ztopí v tom, co vyvře z cév.<br />
                <br />
                <em style="font-size:.8em;text-align: right">D.&nbsp;Alighieri: Božská komedie. Peklo&nbsp;XII, 46-50 (přel. V.&nbsp;Mikeš); A.&nbsp;Cotti: Dante a&nbsp;Verona, 1879.</em><br /><br /> 
            </p>
		</div>
	</div>
</section>