<section id="heslodne" class="features" style="background-image: url(img/HD-2023-02-svatopost-2.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Objetí pokoje</span>
			</h2>
			<br>
            <p>
                Já: „Odpusť mi, jsem hříšník.“<br>
                Ty: „Bůh odpouští, i&nbsp;já dopouštím.“<br>
                <br>
                Ty: „Odpusť mi, jsem hříšník.“<br>
                Já: „Bůh odpouští, i&nbsp;já dopouštím.“<br>
                <br>
                <em style="font-size:.8em;text-align: right">podle liturgie Kathara Deutera; Michael Seeley: Dawn's Early Light; Amy Hiley: Non-socially-distanced hug</em><br><br> 
            </p>
		</div>
	</div>
</section>

