<section id="heslodne" class="features" style="background-image: url(img/HD-2007-jiri_dekovna.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
                <span>Cesta vděčnosti</span>
            </h2>
			<br />
		    <br />
            <p>
                Jak by mohl být Bohu vděčný ten, kdo… je slepý k&nbsp;prostým radostem,<br />
                které potkává na každém kroku?&nbsp;… Potřebujeme otevřít oči a&nbsp;zastavit se,<br />
                abychom mohli žít naplno a&nbsp;s&nbsp;vděčností vychutnávat každý malý dar v&nbsp;životě.<br />
                <br />
               <em style="font-size:.8em;text-align: right">František: Christus vivit (2019), čl. 146.</em><br /><br />
            </p>
		</div>
	</div>
</section>