<section id="heslodne" class="features" style="background-image: url(img/HD-2023-12-advent-2.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>A&nbsp;otevřela se nebesa…</span>
			</h2>
			<br>
            <p>
                Je pohodlné žít s&nbsp;Bohem na obláčku:<br>
				neúkoluje, nevyrušuje, nevnáší<br>
				nejistotu do zajetých kolejí života.<br>
				Je svícnem, pod kterým bývá tma.<br>
                <br>
                <em style="font-size:.8em;text-align: right">srov. Jan 1, 51; T. Radcliff: Být živí v Bohu, Praha, 2023. Alexey Kondakov, 2014.</em><br><br> 
            </p>
		</div>
	</div>
</section>

