<section id="heslodne" class="features" style="background-image: url(img/HD-2024-12-vanoce.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Vzešlo nové světlo</span>
			</h2>
			<br>
            <p>
                Víra nahlíží svět v&nbsp;novém světle,<br>
				odhaluje Boží záměry kolem lidského života,<br>
				a&nbsp;na otázky dnešní doby<br>
				vede mysl k&nbsp;lidským řešením.<br>
				<br>
                <em style="font-size:.8em;text-align: right">Gaudium et Spes, čl. 11; Jacob Jansz: Svatá rodina u stolu, 1495.</em><br><br> 
            </p>
		</div>
	</div>
</section>

