<section id="heslodne" class="features" style="background-image: url(img/HD-2025-12-advent.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Naděje</span>
			</h2>
			<br>
            <p>
                Všichni doufáme.<br>
				V&nbsp;srdci každého člověka se skrývá naděje:<br>
				toužíme po dobru a očekáváme dobra,<br>
				ač nevíme, co přinese druhý den.<br>
				<br>
                <em style="font-size:.8em;text-align: right">František: Naděje neklame, čl.&nbsp;1; Maria Gravida (1410)</em><br><br> 
            </p>
		</div>
	</div>
</section>

