<section id="heslodne" class="features" style="background-image: url(img/HD-2022-04-veli.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Nadechnutí k&nbsp;novému životu</span>
			</h2>
			<br />
		    <br />
            <p>
                Od první chvíle do poslední noci<br />
                se stalo to, co už se nestane,<br />
                byl to akt lásky, a&nbsp;lásky tak vroucí:<br />
                Bůh obětoval sebe toho dne,<br />
                aby zas člověk vstal a&nbsp;duše chtěla<br />
                jít k&nbsp;světlu, když mu odpustil to zlé.<br />
                <br />
                <em style="font-size:.8em;text-align: right">D.&nbsp;Alighieri: Božská komedie. Ráj&nbsp;VII, 112-117 (přel. V.&nbsp;Mikeš); WILLYAM</em><br /><br /> 
            </p>
		</div>
	</div>
</section>

