<section id="heslodne" class="features" style="background-image: url(img/HD-2021-05-mezi.webp); background-color: #9a7e71; background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Ždibec radosti a&nbsp;naděje</span>
			</h2>
			<br />
            <br />
            <p>
                Mnohá společenství je možné rozvíjet v&nbsp;různosti.<br />
                Uskutečňují je šlechetní lidé, kteří mají odvahu<br />
                vystoupit nad konfliktní rovinu<br />
                a&nbsp;pohlížet na druhé v jejich nejhlubší důstojnosti.<br />
               <br />
               <em style="font-size:.8em;text-align: right">František: Evangelii gaudium (2013), čl.&nbsp;228</em><br /><br /> 
            </p>
		</div>
	</div>
</section>