<section id="heslodne" class="features" style="background-image: url(img/HD-2025-02-kotva_nadeje.webp); background-repeat:no-repeat; background-size: cover; background-color: rgba(195, 0, 74, 0.9); background-blend-mode: multiply;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 0, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Kotva naděje</span>
			</h2>
			<br>
            <p>
				Noc kostelů v <a href="https://www.nockostelu.cz/kostel/1161/" style="color:#aa086a; font:bold;">Světlé nad Sázavou</a> i <a href="https://www.nockostelu.cz/kostel/1911/" style="color:#aa086a; font:bold;">Číhošti</a>.<br>
				<br>
                S&nbsp;důvěrou Pánu Ježíši nám obraz kotvy pomáhá pochopit<br>
				stabilitu a&nbsp;jistotu, kterou máme uprostřed rozbouřených vod života.<br>
				Životní bouře námi zmítají, ale my jsme pevně zakotveni v&nbsp;naději.<br>
				Ona nám umožňuje žít v&nbsp;Kristu a překonat hřích, strach a&nbsp;smrt.<br>
				<br>
                <em style="font-size:.8em;text-align: right">František: Naděje neklame, čl.&nbsp;25; Franz Stoedtner: Großer Schiffsanker</em><br><br> 
            </p>
		</div>
	</div>
</section>

