<section id="heslodne" class="features" style="background-image: url(img/HD-2021-02-svatopost.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>Radost z čistého srdce</span>
			</h2>
			<br />
            <br />
            <p>Jazyk duchovní poezie mluví o <em>radostném zármutku</em><br />
            a <em>prameni půstu</em>. Je to proto, že autentická askeze<br />
            je vždycky radostná, pramenící a zářivá.<br />
               <br />
               <em style="font-size:.8em;text-align: right">Bartoloměj: Svatý a Velký půst (2020); Carl Spitzweg: Popeleční středa (1860)</em><br /><br /> 
            </p>
		</div>
	</div>
</section>

