<section id="heslodne" class="features" style="background-image: url(img/HD-2022-12-advent.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Jak znázornit posvátné?</span>
			</h2>
			<br>
		    <br>
            <p>
                „Moje oči uviděly tvou spásu,<br>
                kterou jsi připravil pro všechny národy.“ (Lk&nbsp;2,&nbsp;30-31)<br>
                <br>
                Pokud Vtělení o něčem vypovídá, tak o&nbsp;tom,<br>
                že naše fyzická těla jsou pro Boha důležitá.<br>
                <br>
                <em style="font-size:.8em;text-align: right">S.&nbsp;Erickson: Honest advent, 2020.</em><br><br> 
            </p>
		</div>
	</div>
</section>

