<section id="heslodne" class="features" style="background-image: url(img/HD-2024-02-svatopost.webp); background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 1; padding-top: .4em;">
        		<span>Boží království u&nbsp;stolu</span>
			</h2>
			<br>
            <p>
                Je mnoho příběhů s&nbsp;Ježíšem u&nbsp;stolu.<br>
				Ježíšovo stolování je nevybíravé,<br>
				pohoršuje farizeje a&nbsp;zákoníky:<br>
				„Tento člověk přijímá hříšníky a&nbsp;jí s&nbsp;nimi.“ (Lk&nbsp;15,&nbsp;2)<br>
				<br>
                <em style="font-size:.8em;text-align: right">srov. G.&nbsp;Ostdiek: Reweaving the Ministries, Collegeville, 2021. Jan Křížek, 1957.</em><br><br> 
            </p>
		</div>
	</div>
</section>

