<section id="heslodne" class="features" style="background-image: url(img/HD-2020-Syrie-red.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
        		<span>#RedWednesday</span>
			</h2>
			<br />
		    <br />
            <p>„Koronavirus spojuje celý svět,<br />
				aby opět pohlédl na křehkost lidského života<br />
				a&nbsp;porozuměl základům své víry.<br />
				Měli bychom mu poděkovat, nebo se ho bát?“<br />
               <br />
               <em style="font-size:.8em;text-align: right">+&nbsp;Samir NASSAR: Pascha 2020 (Damašek, Sýrie)</em><br /><br />
            </p>
		</div>
	</div>
</section>