<section id="heslodne" class="features" style="background-image: url(img/HD-2010-obraz.webp);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .7); ">
			<h2 style="line-height: 0.7; padding-top: .4em;">
                <span>Zeptal se jich: „Čí je to obraz?“</span>
            </h2>
			<br />
		    <br />
            <p>
                Živé uvažování farnosti o&nbsp;sobě samé vede ke srovnání ideálního <i>obrazu</i> církve,<br />
                jak si ji Kristus zamiloval (Ef 5, 27), s&nbsp;její skutečnou <i>tváří</i> v&nbsp;dnešním světě…<br />
                Odtud pramení neutuchající potřeba obnovy: opravy nedostatků,<br />
                na které poukazuje a&nbsp;které odmítá svědomí, zrcadlící svůj vzor, Krista.<br />
                <br />
               <em style="font-size:.8em;text-align: right">Mt 22, 20; podle Pavel VI.: Ecclesiam suam (1964), čl. 9–11.</em><br /><br />
            </p>
		</div>
	</div>
</section>