<section id="heslodne" class="features" style="background-image: url(img/HD-Toufar.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
        		<span>3.&nbsp;neděle advetní v Číhošti</span>
			</h2>
			<br />
		    <br />
            <p><b>Mše sv.</b> a&nbsp;<b>beseda</b> o&nbsp;postupu blahořečení Josefa Toufara (M.&nbsp;Doležal, T.&nbsp;Petráček)<br />
               <br />
            </p>
		</div>
	</div>
</section>