<section id="heslodne" class="features" style=" background-image: url(img/advent.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne">
			<h2>
				Advent.
			</h2>
			<br />
			<p>
				<br />
				V den šestý člověk stvořen byl,<br />
				a kdyby si byl zachoval<br />
				podobu, již mu vtiskl Bůh,<br />
				byl by moh’ vždy žít blaženě.<br />
				<br />
				Však k lidstva spáse Stvořitel<br />
				sám na svět musil sestoupit<br />
				v takovém těle, v jakém kdys<br />
				v den šestý člověk stvořen byl.<br />
				<br />
				<em>Beda Ctihodný: Prima creator sæculi…</em>
				<br />
			</p>
		</div>
	</div>
</section>