<section id="heslodne" class="features" style="background-color: #28074f;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
        <img src="img/HD-advent.png" style="width: 30rem; padding-bottom: 4rem; display: block; margin-left: auto; margin-right: auto;">
        <div class="heslodne" style="color: #c7a720; ">
			<h2>
        		<span>Advent</span>
			</h2>
			<br />
		    <br />
            <p>Dopřej mi chuť k&nbsp;jídlu, Pane,<br />
                a&nbsp;také něco, co bych jed,<br />
                dej mi zdravé tělo, Pane,<br />
                a&nbsp;nauč mě s ním zacházat.<br />
                <br />
               <em style="font-size:.8em;text-align: right">Thomas H. B. Webb (1898–1917)</em><br /><br />
            </p>
        </div>
	</div>
</section>