<section id="heslodne" class="features" style="background-image: url(img/HD-cestasvatosti.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
        		<span>Osobité cesti svatosti.</span>
			</h2>
			<br />
		    <br />
            <p>Každý věřící musí rozpoznat svoji vlastní cestu křesťanského života.<br />
                Dát vzejít tomu nejlepšímu ze sebe<br />
                – nejosobnějším Božím darům ve svém srdci (srv. 1 Kor 12,7) –<br />
                a beznadějně nenapodobovat něco, co mu nebylo určeno.<br />
               <br />
               <em style="font-size:.8em;padding-left:30em;text-align: right">Gaudete et exsultate, čl.&nbsp;11</em><br />
            </p>
		</div>
	</div>
</section>