<section id="heslodne" class="features" style="background-image: url(img/HD-Lee-Miller_1937.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
        		<span>Bůh je neustálá novost.</span>
			</h2>
			<br />
		    <br />
            <p>Potřebujeme podnět Ducha svatého,<br />
                abychom nebyli ochromeni strachem a&nbsp;přemrštěnou opatrností<br />
                a&nbsp;nezvykli si chodit jenom po bezpečným cestách.<br /><br />
                Bůh je neustálá novost.<br />
                Pobízí nás, abychom hledali nové způsoby,<br />
                překročili, co důvěrně známe,<br />
                a&nbsp;setkali se s&nbsp;periferií a&nbsp;hraničními oblastmi.<br />
                <br />
               <em style="font-size:.8em;text-align: right">podle Gaudete et Exultate, čl. 133.135</em><br /><br />
            </p>
		</div>
	</div>
</section>