<section id="heslodne" class="features" style=" background-image: url(img/HD-postAbraham.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
				Abrahám a Sára.
			</h2>
			<br />
			<p>
				<br />
                Hospodin řekl Abramovi: „Odejdi. Opusť. Vydej se. Požehnám ti.“<br />
                <em style="text-align:right;">srov.&nbsp;Gn&nbsp;12,&nbsp;1</em><br />
                <br />
                Ježíš hlásal: „Změňte se. Obraťte se. Přiblížilo se nebeské království.“<br />
                <em>srv.&nbsp;Mt&nbsp;4,&nbsp;17</em><br />
				
				
			</p>
		</div>
	</div>
</section>