<section id="heslodne" class="features" style=" background-image: url(img/HD-postAbraham.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
				Svatopostní doba.
			</h2>
			<br />
			<p>
				<br />
                Hospodin řekl Abramovi: „Odejdi. Opusť. Vydej se. Požehnám ti.“
                <em style="font-size:.8em;padding-left:1em;">srov.&nbsp;Gn&nbsp;12,&nbsp;1</em><br />
                <img src="./img/picasso-camel.svg" style="width:3em;padding:1em 0" title="Pablo Picasso: Velbloud, 1907"><br />
                Ježíš hlásal: „Změňte se. Obraťte se. Přiblížilo se nebeské království.“
                <em style="font-size:.8em;padding-left:1em;">srv.&nbsp;Mt&nbsp;4,&nbsp;17</em><br />

			</p>
		</div>
	</div>
</section>