<section id="heslodne" class="features" style="background-color: #970707">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
        		<span>#RedWednesday</span>
			</h2>
			<br />
		    <br />
            <p>„I&nbsp;když svět zapomene na Sýrii,<br />
                Pán nedovolí, aby loď církve potopila.<br />
                Děkujeme, že jste se připojili<br />
                k&nbsp;modlitbě před božským Dítětem, Knížetem pokoje.“<br />
               <br />
               <em style="font-size:.8em;text-align: right">+&nbsp;Samir NASSAR: Noël 2018 (Damašek, Sýrie)</em><br /><br />
            </p>
		</div>
	</div>
</section>