<section id="heslodne" class="features" style=" background-image: url(img/0plech2.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne">
			<h2>
        		<span>Světlo víry.</span>
			</h2>
			<br />
		    <br />
			<p>Každý křesťan a&nbsp;každé společenství <br /> budou rozlišovat, jakou cestu od nich Pán žádá, <br />
				nicméně všichni jsme pozváni přijmout toto povolání: <br />
				vykročit z&nbsp;vlastního pohodlí <br />a&nbsp;mít odvahu vydat se do všech periferií, které potřebují světlo evangelia. <br />
				<em>(Evangelii gaudium, čl.&nbsp;20)</em>
            </p>
		</div>
	</div>
</section>