<section id="heslodne" class="features" style="background-color:#660319;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2 style="text-transform: uppercase; font-size:8em;">
				Svatý týden
			</h2>
			<br />
			<p style="font-size:3em;line-height: 120%;">
                <br />
                <br />
                <a href="#Velikonoce2018" style="color:black;">Obřady na Míčově&nbsp;&nbsp;<i class="fas fa-external-link-alt" style="font-size:0.6em;color:rgb(32, 32, 32)"></i></a><br />
                <a href="#Velikonoce20184" style="color:black;">Žalmy na Seči&nbsp;&nbsp;<i class="fas fa-external-link-alt" style="font-size:0.6em;color:rgb(32, 32, 32)"></i></a>
                
				<br />
			</p>
		</div>
	</div>
</section>