<section id="heslodne" class="features" style="background-image: url(img/HD-vanoce2018.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
                <span>Hledání místa.</span>
            </h2>
			<br />
		    <br />
            <p>Když se jí naplnil čas, porodila svého syna.<br />
                Zavinula ho do plenek,<br />
                ale nemohla pro něj najít místo,<br />
                kam by ho uložila.<br />
                <br />
               <em style="font-size:.8em;text-align: right">podle „Viacrucis del Migrante“ a&nbsp;Lk&nbsp;2,&nbsp;7</em><br />
            </p>
		</div>
	</div>
</section>