<section id="heslodne" class="features" style=" background-image: url(img/2017-vanoce.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
				Zrození Krista.
			</h2>
			<br />
			<p>
				<br />
				Vy, kteří Krista hledáte,<br />
				do výše oči zdvihněte:<br />
				Tam bude možné uvidět<br />
				znamená slávy pro náš svět.<br />
				<br />
				To je ten vládce národů<br />
				a židovského lidu král,<br />
				Abrahamovi přiřčený<br />
				a jeho rodu navěky.<br />
				<br />
				<em>Prudentius: Quicumque Christum quæritis…</em>
				<br />
			</p>
		</div>
	</div>
</section>