<section id="heslodne" class="features" style="background-image: url(img/2018-vzkriseni2.jpg); background-repeat:no-repeat; background-size: cover; background-position:center center;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black;">
			<h2>
				Setkání se Vzkříšeným.
			</h2>
			<br />
			<p>
				<br />
                Dva učedníci <span style="font-weight:600;">vypravovali</span> ostatním,<br />
                co se jim přihodilo<br />
                na cestě&nbsp;z Jeruzaléma do nedalekých Emauz<br />
                a&nbsp;jak v&nbsp;neznámém člověku <span style="font-weight:600;">poznali</span> Ježíše<br />
                podle způsobu <span style="font-weight:600;">lámání chleba</span>.<br />
                
                <em style="font-size:.8em;padding-left:1em;">srov.&nbsp;Lk&nbsp;24,&nbsp;35</em><br />
			</p>
		</div>
	</div>
</section>