<section id="heslodne" class="features" style="background-image: url(img/HD-vaclav.jpg);  background-repeat:no-repeat; background-size: cover;">
	<div class="container" style="margin-top: auto; margin-bottom: auto;">
		<div class="heslodne" style="color:black; background-color: rgba(255,255, 255, .6)">
			<h2>
        		<span>Svatováclavská pouť</span>
			</h2>
			<br />
		    <br />
            <p>Boleslav řekl Václavovi:<br />
                „Proč chceš odejít, bratře?<br />
                Vždyť máme i&nbsp;zdravý nápoj.“<br />
               <br />
               <em style="font-size:.8em;text-align: right">I. staroslověnská legenda o&nbsp;sv.&nbsp;Václavu, odst.&nbsp;4</em><br /><br />
            </p>
		</div>
	</div>
</section>