<div class="psalm-name">Žalm 111 (110)</div>
<div class="psalm-subtitle">Veliké skutky Boží </div>
<div class="psalm-idea"><i>Veliké a podivuhodné jsou tvé skutky, Pane, Bože vševládný!</i> (Zj 15,3)</div>
<p class="verse start first"><sup>1</sup>Oslavím Hospodina celým srdcem&nbsp;*</p>
<p class="verse cont last">ve sboru spravedlivých i&nbsp;ve shromáždění.</p>

<p class="verse start"><sup>2</sup>Veliká jsou Hospodinova díla,&nbsp;*</p>
<p class="verse cont">ať o&nbsp;nich uvažují všichni, kteří je milují.</p>
<p class="verse start"><sup>3</sup>Velebnost a vznešenost je jeho dílo&nbsp;*</p>
<p class="verse cont">a jeho spravedlnost zůstává navěky.</p>
<p class="verse start"><sup>4</sup>Památku ustanovil na své divy,&nbsp;*</p>
<p class="verse cont">Hospodin je milosrdný a dobrotivý.</p>
<p class="verse start"><sup>5</sup>Dal pokrm těm, kdo se ho bojí,&nbsp;*</p>
<p class="verse cont last">neustále bude pamatovat na svou smlouvu.</p>

<p class="verse start"><sup>6</sup>Své mocné činy ukázal svému lidu,&nbsp;*</p>
<p class="verse cont">když jim dal majetek pohanů.</p>
<p class="verse start"><sup>7</sup>Skutky jeho rukou jsou věrné a spravedlivé,&nbsp;*</p>
<p class="verse cont">spolehlivé jsou všechny jeho příkazy,</p>
<p class="verse start"><sup>8</sup>pevné navěky, navždy,&nbsp;*</p>
<p class="verse cont last">provedené v&nbsp;pravdě a právu.</p>

<p class="verse start"><sup>9</sup>Vykoupení seslal svému lidu,&nbsp;†</p>
<p class="verse cont">sjednal navěky svou smlouvu;&nbsp;*</p>
<p class="verse cont">svaté a velebné je jméno jeho.</p>
<p class="verse start"><sup>10</sup>Počátek moudrosti je bát se Hospodina:&nbsp;†</p>
<p class="verse cont">moudře jednají všichni, kdo tak činí;&nbsp;*</p>
<p class="verse cont">jeho chvála zůstává navždy.</p>

<p class="verse start first">Sláva Otci i&nbsp;Synu&nbsp;*</p>
<p class="verse cont">i&nbsp;Duchu Svatému,</p>
<p class="verse start">jako byla na počátku, i&nbsp;nyní i&nbsp;vždycky&nbsp;*</p>
<p class="verse cont">a na věky věků. Amen.</p>