<div class="psalm-name">Žalm 112 (111)</div>
<div class="psalm-subtitle">Štěstí spravedlivých</div>
<div class="psalm-idea"><i>Žijte jako děti světla. Ovoce světla záleží ve všestranné dobrotě, spravedlnosti a v&nbsp;životě podle pravdy.</i> (Ef 5,8.9)</div>

<p class="verse start first"><sup>1</sup>Blaze muži, který se bojí Hospodina,&nbsp;*</p>
<p class="verse cont">který má velkou zálibu v&nbsp;jeho přikázáních.</p>
<p class="verse start"><sup>2</sup>Mocné bude na zemi jeho potomstvo,&nbsp;*</p>
<p class="verse cont">pokolení řádných lidí bude požehnáno.</p>
<p class="verse start"><sup>3</sup>Hojnost a bohatství budou v&nbsp;jeho domě&nbsp;*</p>
<p class="verse cont last">a jeho štědrost potrvá navždy.</p>

<p class="verse start"><sup>4</sup>Září v&nbsp;temnotách jako světlo řádným lidem,&nbsp;*</p>
<p class="verse cont">je milosrdný, dobrotivý a spravedlivý.</p>
<p class="verse start"><sup>5</sup>Blaze muži, který se slitovává a půjčuje,&nbsp;*</p>
<p class="verse cont">stará se o&nbsp;své věci podle práva.</p>
<p class="verse start"><sup>6</sup>Neboť navěky nezakolísá,&nbsp;*</p>
<p class="verse cont last">ve věčné paměti bude spravedlivý.</p>

<p class="verse start"><sup>7</sup>Nemusí se obávat zlé zprávy,&nbsp;*</p>
<p class="verse cont">jeho srdce je pevné, důvěřuje v&nbsp;Hospodina.</p>
<p class="verse start"><sup>8</sup>Jeho srdce je zmužilé, nebojí se,&nbsp;*</p>
<p class="verse cont">dokud neuzří své protivníky ve zmatku.</p>
<p class="verse start"><sup>9</sup>Rozděluje, dává chudým,&nbsp;†</p>
<p class="verse cont">jeho štědrost potrvá navždy,&nbsp;*</p>
<p class="verse cont last">jeho moc poroste v&nbsp;slávě.</p>

<p class="verse start"><sup>10</sup>Uzří to hříšník a rozzlobí se,&nbsp;†</p>
<p class="verse cont">bude skřípat zuby a zchřadne;&nbsp;*</p>
<p class="verse cont">zajde touha bezbožníků.</p>

<p class="verse start first">Sláva Otci i&nbsp;Synu&nbsp;*</p>
<p class="verse cont">i&nbsp;Duchu Svatému,</p>
<p class="verse start">jako byla na počátku, i&nbsp;nyní i&nbsp;vždycky&nbsp;*</p>
<p class="verse cont">a na věky věků. Amen.</p>