<div class="psalm-name">Žalm 114 (113 A)</div>
<div class="psalm-subtitle">Boží divy při východu z&nbsp;Egypta</div>
<div class="psalm-idea"><i>Buďte si vědomi, že i&nbsp;vy jste vyšli z&nbsp;Egypta, když jste se odřekli tohoto světa.</i> (Sv. Augustin)</div>

<p class="verse start first"><sup>1</sup>Když vytáhl Izrael z&nbsp;Egypta,&nbsp;*</p>
<p class="verse cont">Jakubův dům z&nbsp;cizáckého lidu,</p>
<p class="verse start"><sup>2</sup>stal se Juda Boží svatyní,&nbsp;*</p>
<p class="verse cont last">Izrael Božím panstvím.</p>

<p class="verse start"><sup>3</sup>Moře to vidělo a prchlo,&nbsp;*</p>
<p class="verse cont">Jordán se obrátil nazpět,</p>
<p class="verse start"><sup>4</sup>Hory poskočily jako berani,&nbsp;*</p>
<p class="verse cont last">pahorky jako jehňata.</p>

<p class="verse start"><sup>5</sup>Co je ti, moře, že prcháš,&nbsp;*</p>
<p class="verse cont">Jordáne, že se obracíš nazpět,</p>
<p class="verse start"><sup>6</sup>hory, proč poskakujete jako berani,&nbsp;*</p>
<p class="verse cont last">pahorky, proč skáčete jako jehňata?</p>

<p class="verse start"><sup>7</sup>Země, třes se před Pánem,&nbsp;*</p>
<p class="verse cont">před Bohem Jakubovým,</p>
<p class="verse start"><sup>8</sup>jenž mění skálu v&nbsp;bažinu,&nbsp;*</p>
<p class="verse cont">křemen v&nbsp;prameny vod.</p>

<p class="verse start first">Sláva Otci i&nbsp;Synu&nbsp;*</p>
<p class="verse cont">i&nbsp;Duchu Svatému,</p>
<p class="verse start">jako byla na počátku, i&nbsp;nyní i&nbsp;vždycky&nbsp;*</p>
<p class="verse cont">a na věky věků. Amen.</p>