<div class="psalm-name">Žalm 115 (113 B)</div>
<div class="psalm-subtitle">Chvála náleží jedině Bohu</div>
<div class="psalm-idea"><i>Obrátili jste se od model k&nbsp;Bohu, abyste sloužili Bohu živému a pravému.</i> (1 Sol 1,9)</div>

<p class="verse start first"><sup>1</sup>Nikoli nám, Hospodine, nikoli nám,&nbsp;†</p>
<p class="verse cont">ale svému jménu zjednej slávu&nbsp;*</p>
<p class="verse cont">pro své milosrdenství, pro svou věrnost!</p>
<p class="verse start"><sup>2</sup>Proč mají pohané říkat:&nbsp;*</p>
<p class="verse cont">„Kdepak je ten jejich Bůh?“</p>
<p class="verse start"><sup>3</sup>Bůh náš je na nebesích,&nbsp;*</p>
<p class="verse cont last">učinil všechno, co chtěl.</p>

<p class="verse start"><sup>4</sup>Jejich modly jsou stříbro a zlato,&nbsp;*</p>
<p class="verse cont">dílo lidských rukou.</p>
<p class="verse start"><sup>5</sup>Mají ústa, ale nemluví,&nbsp;*</p>
<p class="verse cont">mají oči, ale nevidí.</p>
<p class="verse start"><sup>6</sup>Mají uši, ale neslyší,&nbsp;*</p>
<p class="verse cont">mají nos, ale nečichají.</p>
<p class="verse start"><sup>7</sup>Mají ruce, ale nehmatají,&nbsp;†</p>
<p class="verse cont">mají nohy, ale nechodí,&nbsp;*</p>
<p class="verse cont">hlas nevydávají svým hrdlem.</p>
<p class="verse start"><sup>8</sup>Jim jsou podobni ti, kdo je zhotovují,&nbsp;*</p>
<p class="verse cont last">každý, kdo v&nbsp;ně doufá.</p>

<p class="verse start"><sup>9</sup>Izraelův dům doufá v&nbsp;Hospodina,&nbsp;*</p>
<p class="verse cont">je jim pomocníkem a štítem.</p>
<p class="verse start"><sup>10</sup>Árónův dům doufá v&nbsp;Hospodina,&nbsp;*</p>
<p class="verse cont">je jim pomocníkem a štítem.</p>
<p class="verse start"><sup>11</sup>Hospodinovi ctitelé doufají v&nbsp;Hospodina,&nbsp;*</p>
<p class="verse cont last">je jim pomocníkem a štítem.</p>

<p class="verse start"><sup>12</sup>Hospodin na nás pamatuje&nbsp;*</p>
<p class="verse cont">a požehná nám,</p>
<p class="verse start">požehná domu Izraelovu,&nbsp;*</p>
<p class="verse cont">požehná domu Árónovu,</p>
<p class="verse start"><sup>13</sup>požehná Hospodinovým ctitelům,&nbsp;*</p>
<p class="verse cont last">malým i&nbsp;velkým.</p>

<p class="verse start"><sup>14</sup>Hospodin vás rozmnoží,&nbsp;*</p>
<p class="verse cont">vás i&nbsp;vaše syny.</p>
<p class="verse start"><sup>15</sup>Požehnáni jste od Hospodina,&nbsp;*</p>
<p class="verse cont">který učinil nebe i&nbsp;zemi.</p>
<p class="verse start"><sup>16</sup>Nebesa jsou nebem pro Hospodina,&nbsp;*</p>
<p class="verse cont">avšak zemi dal lidským dětem.</p>
<p class="verse start"><sup>17</sup>Mrtví nemohou chválit Hospodina,&nbsp;*</p>
<p class="verse cont">nikdo z&nbsp;těch, kteří sestupují do podsvětí.</p>
<p class="verse start"><sup>18</sup>My však velebíme Hospodina,&nbsp;*</p>
<p class="verse cont">nyní až navěky.</p>

<p class="verse start first">Sláva Otci i&nbsp;Synu&nbsp;*</p>
<p class="verse cont">i&nbsp;Duchu Svatému,</p>
<p class="verse start">jako byla na počátku, i&nbsp;nyní i&nbsp;vždycky&nbsp;*</p>
<p class="verse cont">a na věky věků. Amen.</p>