<?php

$nedele="19. neděle v mezidobí";
$datum="8. srpen 2021";
$tyden="3";
$hymnus="hymn-Koi_106.inc";
$cteni= array("1 Petr 1, 13-25", "Buďte svatí!");
$antPM= "Já jsem chléb živý, který sestoupil z nebe. Kdo bude jíst tento chléb, bude žít navěky. Chléb, který já dám, je mé tělo, obětované za život světa.";
$modlitba= "Všemohoucí, věčný Bože, tys nám poslal Ducha svého Syna a přijal jsi nás za vlastní; a proto k tobě smíme volat jako k Otci: upevni, co jsi v nás započal, abychom se mohli ujmout zaslíbeného dědictví. Prosíme o to skrze tvého Syna Ježíše Krista, našeho Pána, neboť on s tebou v jednotě Ducha Svatého žije a kraluje po všechny věky věků.";

?>