<?php

$nedele="28. neděle v mezidobí";
$datum="10. říjen 2021";
$tyden="4";
$hymnus="hymn-Koi_25.inc";
$cteni= array("Žid 12, 14-29", "Varování před odmítnutím naslouchat Božímu hlasu.");
$antPM= "Vy, kteří jste opustili všechno a následovali jste mě, stokrát víc dostanete a za podíl budete mít život věčný.";
$modlitba= "Prosíme tě, Bože, dej nám svou milost, aby nás vždycky předcházela a provázela a stále nás vedla ke konání dobra. Skrze tvého Syna Ježíše Krista, našeho Pána, neboť on s tebou v jednotě Ducha Svatého žije a kraluje po všechny věky věků.";

?>