<?php

$nedele="3. neděle v mezidobí";
$datum="23. leden 2022";
$tyden="3";
$hymnus="hymn-Koi_74a.inc";
$cteni= array("1 Petr 1, 3-12", "Díky Bohu za skvělou naději.");
$antPM= "Dnes se naplnilo Písmo, které jste právě slyšeli.";
$modlitba= "Všemohoucí, věčný Bože, veď nás, ať žijeme podle tvé vůle, abychom zůstávali stále spojeni s tvým milovaným Synem a přinášeli hojný užitek. Skrze tvého Syna Ježíše Krista, našeho Pána, neboť on s tebou v jednotě Ducha Svatého žije a kraluje po všechny věky věků.";
$antifona="ant-Zdrava_bud.inc";

?>