<p class="redsmall">ZDRÁVA BUĎ, KRÁLOVNO NEBE</p>
<p style="font-style:italic; font-weight:400; text-align: right;">T:&nbsp;lat. Ave, Regina cælorum, autor neznámý, 12. století; N:&nbsp;Dum iubar astris oritur, 1505 (<abbr title="(Červený hymnář) Denní modlitba církve. Hymny, Praha, 1988">ČH</abbr>&nbsp;363)</p>
<img src="zdrava_bud_kralovno_nebe.webp" alt="Zdráva buď, Královno nebe" style="width: 100%; padding: 1em 0 1em 0;" />
<div class="hymn">

<p class="first">Zdráva buď, Královno nebe,</p>
<p>andělů sbory ctí tebe,</p>
<p>zdráva buď, nebeská bráno,</p>
<p class="last">z níž světu světlo je dáno.</p>

<p class="first">Plesej, Panno oslavená,</p>
<p>nade všechny vyvolená,</p>
<p>zdráva buď, Panno přečistá,</p>
<p class="last">přimluv se za nás u Krista.</p>



</div>