<p class="redsmall">SALVE REGINA</p>
<p style="font-style:italic; font-weight:400; text-align: right;">Zdrávas, Královno; T:&nbsp;asi Heřman z&nbsp;Reichenau, 11. století; N:&nbsp;chorál (<abbr title="Mešní zpěvy, Praha, 1990">MZ</abbr>&nbsp;1001)</p>
<img src="salve_regina.webp" alt="Salve Regina" style="width: 100%; padding: 1em 0 1em 0;" />
<div class="hymn">

<p class="first">Salve, Regína, <span class="red">*</span> mater misericórdiæ,</p>
<p>vita dulcédo et spes nostra, salve.</p>
<p>Ad te clamámus, éxules, fílii Hevæ.</p>
<p>Ad te suspirámus, geméntes et flentes in hac lacrimárum valle.</p>
<p>Eia ergo, advocáta nostra, illos tuos misericórdes óculos ad nos convérte.</p>
<p>Et Iesum, benedíctum fructum ventris tui, nobis post hoc exílium osténde.</p>
<p>O&nbsp;clemens, o&nbsp;pia, o&nbsp;dulcis Virgo María.</p>


</div>