<div class="hymn">
    <p style="font-style:italic; font-weight:400; text-align: right;">Ježíši, Ty jsi chléb živý; TN: Vojtěch Král (<abbr title="Koinonia, Olomouc, 2016">Koi</abbr>&nbsp;106)</p>
<img src="2021_08_08-Jezizi_Ty_jsi_chleb_zivy.webp" alt="Hymnus" style="width: 100%; padding: 1em 0 1em 0;" />

<p class="first">Ježíši, Ty jsi chléb živý,</p>
<p>který sestoupil na tuto zem,</p>
<p>za pokrm hladových duší</p>
<p class="last">Tělo tvé dává se všem.</p>

<p>Spatří slávu Tvou, kdo Tvé tělo jí,</p> 
<p class="last">Pane, posiluj mou duši ke spasení.</p>

</div>