<div class="hymn">
    <p style="font-style:italic; font-weight:400; text-align: right;">Hosana; TN: <a href="https://en.wikipedia.org/wiki/Carl_Tuttle">Carl Tuttle</a>. Česky: Michal Otřísal, Karel Řezábek (<abbr title="Koinonia, Olomouc, 2016">Koi</abbr>&nbsp;25)</p>
<img src="2021_10_10-hymnus-Hosana.webp" alt="Hymnus" style="width: 100%; padding: 1em 0 1em 0;" />

<p class="first last"><span class="red">1.</span> Hosana, hosana, hosana Bohu na nebi.</p>

<p><span class="red">R.</span> Jméno slavíme Tvé, (haleluja,)</p> 
<p>chválí Tě srdce mé, (haleluja,)</p>
<p class="last">vyvýšen buď, ó Bože náš, hosana Bohu na nebi. (sláva všech králů Králi; chvála Tobě, Pane náš)</p>

<p class="last"><span class="red">2.</span> Sláva, sláva, sláva všech králů Králi.</p>

<p class="last"><span class="red">3.</span> Chvála, chvála, chvála Tobě, Pane náš.</p>

</div>