<div class="hymn">
    <p style="font-style:italic; font-weight:400; text-align: right;"><a href="https://en.wikipedia.org/wiki/El_Shaddai_(song)">El Shaddai</a>; TN: <a href="https://en.wikipedia.org/wiki/Michael_Card">Michael Card</a>, John Thompson; česky: anonym (<abbr title="Koinonia, Olomouc, 2016">Koi</abbr>&nbsp;74a)</p>
<img src="2022_01_23-hymnus-Koi74a.webp" alt="Hymnus" style="width: 100%; padding: 1em 0 1em 0;" />

<p class="first"><span class="red">R.</span> El Šaddaj, El Šaddaj, El, Eljona Adonaj,</p>
<p>od věků až na věky jménem svým jsi veliký.</p>
<p>El Šaddaj, El Šaddaj, Erkamkana Adonaj,</p>
<p class="last">budu vzývat jméno Tvé, El Šaddaj.</p>

<p class="first"><span class="red">1.</span> Láskou svou a Beránkem zachránil jsi Izrael.</p>
<p>Ty jsi mocí ruky své ztišil moře bouřlivé.</p>
<p>Ty jsi byl Bůh vidící klečící</p>
<p class="last">a vyvedl mocí svou dětí své.</p>

<p class="first"><span class="red">2.</span> Mnoho let jsi učil lid, Kristův čas že má přijít,</p>
<p>nikdo z nás však nevěděl, kým by Mesiáš být měl.</p>
<p>V slově svém jsi zjevil plán, že Syn Tvůj má přijít k nám,</p>
<p class="last">aby nejskvělejší čin vykonal.</p>


</div>