<div class="hymn">
    <p style="font-style:italic; font-weight:400; text-align: right;">Fratello sole sorella luna (1972); TN: Riz Ortolani; česky: Pavel Osoha (<abbr title="Hosana 1 (modrá), Praha, 2007">H1</abbr>&nbsp;192)</p>
<img src="2021_06_13-hymnus-pisen_sv_Frantiska-web.webp" alt="Hymnus" style="width: 100%; padding: 1em 0 1em 0;" />

<p class="first"><span class="red">1.</span> Buď veleben, ó Pane můj,</p>
<p>nejvyšší Králi, vše ať zní k chvále tvé.</p>
<p class="last">Za dary dík z tvé dlaně otcovské.</p>

<p><span class="red">2.</span> Za slunce zář, co dává radost všem,</p> 
<p>tisíce hvězd na nebi jiskřivém.</p>
<p class="last">Za větru zpěv i mlhu podzimní.</p>

<p><span class="red">3.</span> Za vodu čistou teď můj dík ti zní.</p>
<p class="last">Za ohně svit, co noci tmu zahání.</p>

<p><span class="red">4.</span> Též, Pane, dík, za zemi mateřskou,</p>
<p>za plodů dar, co na ní vyrostou.</p>
<p class="last">Že hýčká dál a živí děti tvé.</p>

<p><span class="red">5.</span> Tvé děti když stále v lásce zůstanou,</p>
<p class="last">sám nejvyšší jim budeš korunou.</p>

<p><span class="red">6.</span> Buď veleben, ó Pane můj,</p>
<p>nejvyšší Králi, vše ať zní k chvále tvé.</p>
<p class="last">Za dary dík z tvé dlaně otcovské.</p>

</div>